title: Home Assistant Institutska - Сервер
views:
  - title: Главная
    id: main
    icon: mdi:home-assistant
    
    badges:
        - sensor.time
        - sensor.date
        - sensor.maria_db_size
        - person.huskins
        - person.anna

    cards:
      - type: vertical-stack
        cards:
         
        - type: markdown
          content: >
              **Поточний стан**
        
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.online
              name: Сервер перезавантажено
            - entity: sensor.time
              name: Поточний час
              icon: mdi:clock-outline
              
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline

        - type: markdown
          content: >
              **Personal Info**

        - type: iframe
          url: https://alerts.in.ua
          aspect_ratio: 75%
          
        - type: entities
          show_header_toggle: false
          entities:
            - entity: binary_sensor.kyiv_alert
              name: Тривога у Києві


        - type: markdown
          content: >
              **Резервне копіювання**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.last_google_backup_main
            - entity: sensor.backups_in_google_drive
            - entity: sensor.backups_in_home_assistant
            - entity: sensor.size_in_google_drive
            - entity: sensor.size_in_home_assistant

            - entity: binary_sensor.bath_no_motion
            - entity: timer.bath_light_countdown
            - entity: timer.bath_fan_countdown
            - entity: binary_sensor.aqara_presence_sensor_bath_occupancy
            - entity: fan.bath_fan

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.maria_db_size
              name: DB size
              icon: mdi:database
              
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline
     
      - type: vertical-stack
        cards:     
              
        - type: markdown
          content: >
              **Графіки**
              
        - type: horizontal-stack
          cards:
            - type: gauge
              name: Загрузка CPU
              unit: '%'
              entity: sensor.processor_use
              severity:
                green: 0
                yellow: 60
                red: 85
                
            - type: gauge
              name: Загрузка RAM
              unit: '%'
              entity: sensor.memory_use_percent
              severity:
                green: 0
                yellow: 60
                red: 85
        
        - type: horizontal-stack
          cards:       
            - type: gauge
              name: Диск заполнен
              unit: '%'
              entity: sensor.disk_use_percent
              severity:
                green: 0
                yellow: 60
                red: 85
                
            - type: gauge
              name: Загрузка RAM
              unit: 'Gb'
              entity: sensor.disk_free
              severity:
                red: 2
                yellow: 50
                green: 150
            
        - type: history-graph
          entities:
            - entity: sensor.maria_db_size
              name: Maria DB
        
  - title: Погода
    icon: mdi:weather-partly-snowy-rainy    
    cards:
        - type: weather-forecast
          entity: weather.forecast_institutska
          
  - title: Освещение
    icon: mdi:lightbulb-group
    cards:
      - type: vertical-stack
        cards:
            - type: markdown
              content: >
                **Панель переключателей**
                  
            - type: entities
              show_header_toggle: false
              entities:
                - entity: light.yeelight_strip_corridor_mirror
                - entity: light.yeelight_strip_tv_bedroom
                - entity: light.intellect
                - entity: light.bath_light
                - entity: light.living_room_garland_light
                - entity: light.living_room_mirror_light

                - entity: light.dining_room_light
                - entity: light.corridor_light
                - entity: light.front_door_light
                - entity: light.guest_room_light
                - entity: light.bed_room_light
                - entity: light.living_room_main_light
                - entity: light.living_room_back_light

                - entity: input_select.light_mode

                  
            - type: entities
              show_header_toggle: false
              entities:
                - entity: script.light_on_bath
                - entity: script.light_off_bath
                - entity: script.ventilation_on_bath
                - entity: script.ventilation_off_bath
                
      - type: vertical-stack
        cards:
            - type: markdown
              content: >
                **Светильники**
                  
            - type: horizontal-stack
              cards: 
                - type: light
                  entity: light.yeelight_strip_corridor_mirror
                  name: Дзеркало у коридорі
                - type: light
                  entity: light.yeelight_strip_tv_bedroom
                  name: Телевізор у спальні
                - type: light
                  entity: light.intellect
                  name: Лампа вертикальна
                - type: light
                  entity: light.bath_light
                - type: light
                  entity: light.living_room_garland_light
                - type: light
                  entity: light.living_room_mirror_light

  - title: wi-fi
    icon: mdi:wifi
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              **Wi-Fi розетки**
          - type: entities
            show_header_toggle: false
            entities:
              - entity: switch.toggle
                name: Підсвітка дзеркала зал
              - entity: binary_sensor.switch
                name: Підсвітка дзеркала зал
              - entity: switch.toggle_2
                name: Гірлянда зал
              - entity: binary_sensor.switch_2
                name: Підсвітка дзеркала зал

              - entity: script.send_message_1
              - entity: script.system_report
              - entity: sensor.unavailable_now_light
              - entity: sensor.unavailable_now_switch
              - entity: sensor.unavailable_now_sensor
              - entity: sensor.unavailable_now_binary_sensor

    
    
    
    